# Generated by Django 5.2.7 on 2025-10-21 18:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_user',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Business', 'Business'), ('Student', 'Student')], default='Individual', max_length=50),
        ),
    ]
