# Generated by Django 5.2.7 on 2025-10-23 14:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar_alter_profile_type_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/ds1qsfajw/image/upload/v1761071644/avatars/ge0hluzvf07rpdsu2kyd.jpg', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
