# Generated by Django 5.2.7 on 2025-10-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image_url',
            field=models.FileField(upload_to='images/'),
        ),
    ]
