# Generated by Django 5.2.7 on 2025-10-26 09:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtesionScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('input_media', cloudinary.models.CloudinaryField(max_length=255, verbose_name='input_media')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
